### ISSUE TITLE
request for release

### ISSUE THREAD

**Issue by YoheiKakiuchi** [ros/collada_urdf#28]
please release new version solving https://github.com/ros/collada_urdf/pull/27

**Comment by clalancette** [comment]
PRs opened:

https://github.com/ros/rosdistro/pull/17780
https://github.com/ros/rosdistro/pull/17781
https://github.com/ros/rosdistro/pull/17782

**Comment by clalancette** [comment]
And all are merged now, so closing this out.

**Comment by YoheiKakiuchi** [comment]
Thanks @clalancette
