### ISSUE TITLE
Release to indigo, kinetic, and lunar

### ISSUE THREAD

**Issue by sloretz** [ros/collada_urdf#3]
Need to release to change repository URL

**Comment by sloretz** [comment]
And jade since it isn't EOL yet

**Comment by clalancette** [comment]
@sloretz I think this is done now, right?  Can we close this ticket?

**Comment by sloretz** [comment]
Yup! Closing
indigo and jade have version 1.11.14 which is the latest on the indigo-devel branch
kinetic and lunar have version 1.12.10 which is the latest on the kinetic-devel branch.
