### ISSUE TITLE
Error when installing collada_urdf

### ISSUE THREAD

**Issue by jclinton830** [ros/collada_urdf#31]
Hi there, 

I am trying to convert a urdf to .dae by executing the following command:

`rosrun collada_urdf urdf_to_collada <myrobot_name>.urdf <myrobot_name>.dae`

When I do, I end up with the following error: 

[rospack] Error: package 'collada_urdf' not found

I have tried to running rosdep install collada_urdf, that returns the following: 

ERROR: Rosdep cannot find all required resources to answer your query
Missing resource collada_urdf
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/jjustin/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share

So I am running ubuntu 16 inside of VMware, running ROS kinetic and I have compiled openrave from source according to the tutorial  found [here](https://scaron.info/teaching/installing-openrave-on-ubuntu-16.04.html). 

Any help in this matter would be appreciated. 

Thanks.

**Comment by clalancette** [comment]
Sorry for not responding in a timely manner.

What it looks like happened is that you didn't have `ros-kinetic-collada-urdf` installed on your system, and thus it couldn't find it.  You should be able to `sudo apt-get install ros-kinetic-collada-urdf` and then have your `rosrun` command work.

I'm going to close this out, but feel free to comment more or reopen if you are still having problems.

**Comment by Somusundram** [comment]
Hi,

I am facing the same issue.However i am using ROS Melodic. Does it support Ros Melodic?

**Comment by clalancette** [comment]
> I am facing the same issue.However i am using ROS Melodic. Does it support Ros Melodic?

Yes.  Make sure you have `ros-melodic-collada-urdf` installed on your system.
