### ISSUE TITLE
noetic release

### ISSUE THREAD

**Issue by k-okada** [ros/collada_urdf#36]
we could release `collada_urdf` once https://github.com/ros/rosdistro/pull/25140 get merged.

**Comment by k-okada** [comment]
@clalancette could you give me write permission to this repository so that we can release this package udner Ros Orpahed Package Maintainer initiatives? (https://discourse.ros.org/t/ros-orphaned-package-maintainer-info-rep-152-for-review/7906)

**Comment by clalancette** [comment]
Released in https://github.com/ros/rosdistro/pull/25813 ; I'm going to close this out.  Sorry for the delay in responding; it just fell off the radar.
