### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Michaelyangyu** [ros/collada_urdf#40]
Hi 
   I get the following errors and I can't find the error. The command used is:
  rosrun collada_urdf urdf_to_collada "$MYROBOT_NAME".urdf "$MYROBOT_NAME".dae

   I got this error: Segmentation fault (core dumped)

    I'm using ubuntu18.04  ,ROS  melodic .
Could you help me with it?
  Thanks a lot.

**Comment by clalancette** [comment]
What are you passing for `$MYROBOT_NAME`?  I don't see a segfault here, but it may be that something is funky with the URDF you are using.

**Comment by Michaelyangyu** [comment]
I used export export MYROBOT_NAME="ddd_arm"  and my urdf name is ddd_arm.urdf. The 
URDF is working fine in rviz and gazebo， I guess if there is something wrong with my boost version? I  have both 1.58.0 and 1.65.1 versions  in my computer. When  I'm going to  install openrave ,I figure out the boost version must be 1.58.0 . So I installed 1.58.0 .

**Comment by clalancette** [comment]
Sorry, I don't know what `ddd_arm` is.  Maybe its from a package I don't know about.

Having multiple boost versions on your computer definitely sounds like a potential source of issues.  I'd suggest to remove boost 1.58.0 and try this again.

So far, this doesn't seem like a bug in collada_urdf.  For questions like this, please ask at https://answers.ros.org, which is a central place for questions that are later searchable.  I'm going to close this out, but feel free to reopen if you think this is a bug in collada_urdf.
